transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlib final_project_soc
vmap final_project_soc final_project_soc
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/final_project_soc.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_mm_interconnect_0.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_sysid_qsys_0.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_sdram_pll.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_sdram.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_onchip_memory2_0.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_nios2_qsys_0.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_nios2_qsys_0_cpu.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_nios2_qsys_0_cpu_debug_slave_sysclk.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_nios2_qsys_0_cpu_debug_slave_tck.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_nios2_qsys_0_cpu_debug_slave_wrapper.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_nios2_qsys_0_cpu_oci_test_bench.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_nios2_qsys_0_cpu_test_bench.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_jtag_uart_0.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_audio_pll_0.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_up_avalon_reset_from_locked_signal.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_up_altpll.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_up_av_config_serial_bus_controller.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_up_slow_clock_generator.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_up_av_config_auto_init.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_up_av_config_auto_init_ob_de2_115.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_up_av_config_auto_init_ob_audio.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_up_av_config_auto_init_ob_adv7180.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_audio_config.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_up_audio_bit_counter.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_up_audio_in_deserializer.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_up_audio_out_serializer.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_up_clock_edge.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_up_sync_fifo.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_audio.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_LEDR.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_LEDG.v}
vlog -sv -work work +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project {C:/Users/Justin/Documents/ece385/final_project/final_project/VGA_controller.sv}
vlog -sv -work work +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project {C:/Users/Justin/Documents/ece385/final_project/final_project/Color_Mapper.sv}
vlog -sv -work work +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project {C:/Users/Justin/Documents/ece385/final_project/final_project/ball.sv}
vlog -sv -work work +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project {C:/Users/Justin/Documents/ece385/final_project/final_project/HexDriver.sv}
vlog -sv -work work +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project {C:/Users/Justin/Documents/ece385/final_project/final_project/Display.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_irq_clock_crosser.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_irq_mapper.sv}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_avalon_st_handshake_clock_crosser.v}
vlog -vlog01compat -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_avalon_st_clock_crosser.v}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_mm_interconnect_0_rsp_mux_001.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_mm_interconnect_0_rsp_demux_003.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_mm_interconnect_0_rsp_demux_001.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_mm_interconnect_0_cmd_mux_003.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_mm_interconnect_0_cmd_demux_001.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_mm_interconnect_0_router_005.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_mm_interconnect_0_router_002.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_mm_interconnect_0_router_001.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/final_project_soc_mm_interconnect_0_router.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work final_project_soc +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project_soc/synthesis/submodules/altera_merlin_master_translator.sv}
vlog -sv -work work +incdir+C:/Users/Justin/Documents/ece385/final_project/final_project {C:/Users/Justin/Documents/ece385/final_project/final_project/final_project.sv}

